In [1]:
import numpy as np

In [2]:
# crie uma lista
lista = [1,2,3,4,5,6]

# agora transforme ele num array do num py
array = np.array(lista)


In [3]:
# <!-- printando os valores para verificar como a saida é diferente -->

print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [4]:
# mostrando o tipo da lista e do noArray
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
# para printar o valor passando o indice do array fazemos assim
print(array[0])

1


In [6]:
# alterando valor direto pelo indice
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [9]:
# Criando matriz de zeros 5 linhas e 3 colunas
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# exemplo notas de alunos
lista_notas = [9.6 , 5.6, 6.6, 2.5]
notas = np.array(lista_notas)

# trazendo o valor máximo
print("Maximo", notas.max())
# trazendo o valor minimo
print('Mínimo', notas.min())
# desvio padrão 
print("Desvio padrão", notas.std())
# media
print("Média", notas.mean())
# menor posicao
print("Menor posição", notas.argmin())


Maximo 9.6
Mínimo 2.5
Desvio padrão 2.5351282018864447
Média 6.074999999999999
Menor posição 3
